spring.application.name=MusicServer
server.port=8080

spring.datasource.url=jdbc:h2:file:./.local/musicserver-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=520MB

music.storage.root=./.local/music-storage
music.auth.token-ttl-days=30
music.cors.allowed-origins=*
