create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    password_hash varchar(255) not null,
    display_name varchar(120) not null,
    avatar_url varchar(1000),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

alter table app_users add constraint uk_app_users_username unique (username);

create table auth_tokens (
    id bigint generated by default as identity primary key,
    token_hash varchar(64) not null,
    user_id bigint not null,
    expires_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    constraint fk_auth_tokens_user foreign key (user_id) references app_users(id)
);

alter table auth_tokens add constraint uk_auth_tokens_token_hash unique (token_hash);
create index idx_auth_tokens_user_id on auth_tokens(user_id);

create table music_files (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    original_filename varchar(255) not null,
    storage_path varchar(255) not null,
    title varchar(255) not null,
    artist varchar(255),
    album varchar(255),
    content_type varchar(120) not null,
    file_size bigint not null,
    checksum varchar(64) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint fk_music_files_owner foreign key (owner_id) references app_users(id)
);

alter table music_files add constraint uk_music_files_storage_path unique (storage_path);
create index idx_music_files_owner_created_at on music_files(owner_id, created_at desc);

create table playlists (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    name varchar(120) not null,
    description varchar(500),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint fk_playlists_owner foreign key (owner_id) references app_users(id)
);

create index idx_playlists_owner_created_at on playlists(owner_id, created_at desc);

create table playlist_tracks (
    id bigint generated by default as identity primary key,
    playlist_id bigint not null,
    music_id bigint,
    external_source varchar(40),
    external_id varchar(120),
    title varchar(500),
    artist varchar(300),
    album varchar(300),
    pic_url varchar(1000),
    duration bigint,
    sort_order integer not null,
    created_at timestamp(6) with time zone not null,
    constraint fk_playlist_tracks_playlist foreign key (playlist_id) references playlists(id),
    constraint fk_playlist_tracks_music foreign key (music_id) references music_files(id)
);

create index idx_playlist_tracks_playlist_order on playlist_tracks(playlist_id, sort_order, created_at);
create index idx_playlist_tracks_music_id on playlist_tracks(music_id);
create index idx_playlist_tracks_external on playlist_tracks(playlist_id, external_source, external_id);

create table favorite_tracks (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    music_id bigint,
    external_source varchar(40),
    external_id varchar(120),
    title varchar(500),
    artist varchar(300),
    album varchar(300),
    pic_url varchar(1000),
    duration bigint,
    created_at timestamp(6) with time zone not null,
    constraint fk_favorite_tracks_owner foreign key (owner_id) references app_users(id),
    constraint fk_favorite_tracks_music foreign key (music_id) references music_files(id)
);

create index idx_favorite_tracks_owner_created_at on favorite_tracks(owner_id, created_at desc);
create index idx_favorite_tracks_music_id on favorite_tracks(music_id);
create index idx_favorite_tracks_external on favorite_tracks(owner_id, external_source, external_id);

create table transcode_variants (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    music_id bigint not null,
    profile_id varchar(120) not null,
    status varchar(40) not null,
    storage_path varchar(2000),
    file_size bigint,
    checksum varchar(64),
    error_message varchar(1000),
    last_accessed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint fk_transcode_variants_owner foreign key (owner_id) references app_users(id),
    constraint fk_transcode_variants_music foreign key (music_id) references music_files(id),
    constraint uk_transcode_variant_owner_music_profile unique (owner_id, music_id, profile_id)
);

create index idx_transcode_variant_owner_status on transcode_variants(owner_id, status);
create index idx_transcode_variant_status_access on transcode_variants(status, last_accessed_at);
